#!/usr/bin/env bash
set -euo pipefail

usage="$(basename "$0") [-h] [--help] [string] -- convert any string to upper case

DESCRIPTION:
    -h, --help	Show this help message

PRIMARIES:
    string      String to convert
"
usage() {
    echo "$usage"
    exit 1
}

for option in "$@"
do
    case $option in
        -h|--help) usage;;
        -*|--*|\?) printf "illegal option: %s\n\n" "$option" >&2; usage;;
    esac
done

input=
#[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

if [ $# -eq 1 ]; then
    input="$1"
elif [ $# -eq 0 ]; then
    read input
else
    usage
fi

##

echo $input | tr '[:lower:]' '[:upper:]'

exit $?
